# site settings
title: 
subtitle: 
email: loulouwon@gmail.com
description: Welcome to my portfolio site. Nice to meet you.<br>My name is won mi rae.
baseurl:  "" # the subpath of your site, e.g. "/blog"
url: "https://loulouwon.github.io" # the base hostname & protocol for your site
author:
street_address: Gwacheon-daero, Gwacheon-si,
city: Gyeonggi-do
state: ""
zip_code: ""
country: Republic of Korea
phone: 010.6717.5534

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url: https://www.facebook.com/loulouwon
github_url: https://github.com/loulouwon
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/w.mi_rae/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
  
remote_theme : andrewbanchich/forty-jekyll-theme
